### ISSUE TITLE
Runtime error after the exporter successfully starts and fetches workflows

### ISSUE THREAD

**Issue by razvanonet** [Labbs/github-actions-exporter#77]
We have the github actions exporter running inside ECS, using the latest image from ghcr.io/labbs/github-actions-exporter:latest. It worked well until last night but now it started to fail. The task starts well, it authenticates with github and fetches multiple workflows from the repositories, but then after 1 min, it fails with the error below. We think it might have been broken by something externally as it worked fine until now 

```
   2024-03-14T10:15:38.552+02:00  2024/03/14 08:15:38 exporter listening on 0.0.0.0:9999
   2024-03-14T10:18:16.265+02:00  panic: runtime error: invalid memory address or nil pointer dereference
   2024-03-14T10:18:16.265+02:00  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x936780]
   2024-03-14T10:18:16.265+02:00  goroutine 355 [running]:
   2024-03-14T10:18:16.265+02:00  github.com/spendesk/github-actions-exporter/pkg/metrics.getFieldValue({_, _}, {0xc002b58550, 0xc002c04f60, 0xc002c04f70, 0x0, 0xc002c04f80, 0xc002b58558, 0xc002b585e0, 0xc002c04f90, ...}, ...)
   2024-03-14T10:18:16.265+02:00  /app/pkg/metrics/get_workflow_runs_from_github.go:25 +0x420
   2024-03-14T10:18:16.265+02:00  github.com/spendesk/github-actions-exporter/pkg/metrics.getRelevantFields({0xc000339ec0, 0x26}, 0xc002803560)
   2024-03-14T10:18:16.265+02:00  /app/pkg/metrics/get_workflow_runs_from_github.go:57 +0x177
   2024-03-14T10:18:16.265+02:00  github.com/spendesk/github-actions-exporter/pkg/metrics.getWorkflowRunsFromGithub()
   2024-03-14T10:18:16.265+02:00  /app/pkg/metrics/get_workflow_runs_from_github.go:125 +0x2ac
   2024-03-14T10:18:16.265+02:00  created by github.com/spendesk/github-actions-exporter/pkg/metrics.InitMetrics
   2024-03-14T10:18:16.265+02:00  /app/pkg/metrics/metrics.go:67 +0x471
```

**Comment by razvanonet** [comment]
the issue is fixed now, we did not do anything on our side.
